### ISSUE TITLE
True will be a reserve word in PHP7

### ISSUE THREAD

**Issue by nyamsprod** [true/php-punycode#10]
[According to this RFC](https://wiki.php.net/rfc/reserve_more_types_in_php_7) in voting phase `True` is to become a reserved word starting with PHP7. Which means that a namespace change should be made if we want the library to work in PHP7+

**Comment by JustBlackBird** [comment]
+1 The first alpha version of PHP7 will be released in June. Thus we should make a decision on the issue as soon as possible.

**Comment by renan** [comment]
Yep. Alpha 1 was just released a couple of days ago. I believe it is wise to make this library run on PHP7.

By the end of the week we are going to namespace it again and release a 2.0 version.

**Comment by JustBlackBird** [comment]
Thank you @renan ! Waiting for new release.
