### ISSUE TITLE
Twig extension?

### ISSUE THREAD

**Issue by EmanueleMinotto** [true/php-punycode#15]
What about including in this repository a Twig extension for methods `encode` and `decode`?
I'm currently thinking to a couple of filters `punycode_encode` and `punycode_decode`.
Of course I can send a PR if it's interesting.

**Comment by renan** [comment]
I would like to keep this package scope very clean, without any code that is not needed. Unfortunately it means we won't be accepting such PR.

Instead I suggest to, rather than fork this repo, create a `punycode-twig` package offering such ability.
