### ISSUE TITLE
Cannot decode domain in uppercase

### ISSUE THREAD

**Issue by abcdmitry** [true/php-punycode#16]
Library doesn't parse encoded domain in uppercase like `XN--D1ABBGF6AIIY.XN--P1AI`
However domains in uppercase form are mentioned in many places including IANA domains list http://data.iana.org/TLD/tlds-alpha-by-domain.txt

I think uppercased domains should be treated as valid as well

**Comment by abcdmitry** [comment]
I have investigated php native idn_to_utf8 function - it works with uppercase domains.
So I've created pull request #17 with necessary fix for the handling of uppercase encoded domains

**Comment by renan** [comment]
Fixed by #17.
