### ISSUE TITLE
Proposal to move to symfony/polyfill

### ISSUE THREAD

**Issue by nicolas-grekas** [true/php-punycode#28]
Hi,
would you consider moving the code in this repo as a polyfill in http://github.com/symfony/polyfill/?
I didn't check how far the implementation is from `idn_to_ascii` and `idn_to_utf8`, but I'd be happy to help refactor it as a true polyfill for these functions.
WDYT?
/cc @fabpot

**Comment by fabpot** [comment]
Work is happening here: https://github.com/symfony/polyfill/pull/149

**Comment by nicolas-grekas** [comment]
Implemented and released in `symfony/polyfill`.
