### ISSUE TITLE
Abandon in favor of symfony/polyfill-intl-idn?

### ISSUE THREAD

**Issue by nicolas-grekas** [true/php-punycode#30]
Follow up of https://github.com/true/php-punycode/issues/28: the `symfony/polyfill-intl-idn` package now implements the `idn_to_ascii` and `idn_to_utf8` functions.

Since this repo is not maintained anymore, maybe it should be declared as abandoned here and on packagist?

**Comment by ceeram** [comment]
Not actively maintained, but still used. Abandoning is not required in order for symfony/polyfill-intl-idn to live as alternative.

Will update project description, to link to new package for people seeking actively maintained punycode library
